name: Deploy Hello World Notebook to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/python-notebook-automation/hello-notebook .
          docker push gcr.io/python-notebook-automation/hello-notebook

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-notebook \
            --image gcr.io/python-notebook-automation/hello-notebook \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
