name: Deploy Hello Notebook

on:
  push:
    branches: [ main ]  # or whichever branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook .

    - name: Push Docker image
      run: docker push us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy hello-notebook \
          --image us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
